// <auto-generated />
namespace Movies_Rent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class intialModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(intialModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201901241315475_intialModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
